/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first.hibernate.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals(true, classUnderTest.someLibraryMethod());
    }
}
